### ISSUE TITLE
현재 해결이 필요한 사항

### ISSUE THREAD

**Issue by jhparkland** [datascience-labs/datascience-labs.github.io#1]
1. debs 프로젝트는 제가 권한이 없어서 추가할 수 없습니다.
2. papers - 2021 - 태양광 EV 주차장 기반 유통매장을 위한 실시간 대시보드 이미지 파일 손상되어있습니다.
3. project 접속 불가 -> ./gitignore에서 Project관련 항목 주석 해제 후 해결했습니다.
4. projects index가 없음(ignore 처리 되어있었음). -> 임시로 만들었습니다. 

4번 때문에 새롭게 프로젝트를 추가해도 홈페이지에 나타나지 않습니다.

**Comment by chunsejin** [comment]
projects updates는 다음과 같습닏자
1. _config.yml 에 git repo 세팅(권한이 있어야함)
2. ruby _scripts/ update-and_preprocess.rb  # _config에 있는 git repo들을 clone 
3. ruby _scripts/ process-markdown.rb # md 파일들에 대해서 처리 없으면 수행 안됨 
4. ruby _scripts/  generate-project-data # build를 위한 프로젝트 데이터 생성
