### ISSUE TITLE
next issues

### ISSUE THREAD

**Issue by jhparkland** [datascience-labs/datascience-labs.github.io#21]
1. Contact
     - 랩장 이메일 수정(김정수 -> 이성범)
2. Join
	- 이메일 하이퍼링크 적용
4. blog 
	- 게시글 하단에 구분선 

간단한 작업이라 여유 시간에 할 수 있을 것 같습니다.

**Comment by chunsejin** [comment]
Contact
랩장 이메일 수정(김정수 -> 이성범)
Join
이메일 하이퍼링크 적용

**Comment by chunsejin** [comment]
solved
